# Generated by Django 4.1.3 on 2022-11-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyroo', '0002_product_boy_pant_product_boy_shirt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='boy_pant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='boy_shirt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='girl_dress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='girl_skirt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='men_jacket',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='men_trench',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='women_blouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='women_dress',
            field=models.BooleanField(default=False),
        ),
    ]
